name: 'Setup Misc Configs'
description: 'Set up kernel configuration fragment with miscellaneous options'
inputs:
  kernel_version:
    description: 'Kernel version (e.g., 6.1)'
    required: true
  android_version:
    description: 'Android version (e.g., android14)'
    required: true
  sublevel:
    description: 'Sublevel of kernel version (e.g., 1)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Apply Kernel Configuration
      shell: bash
      run: |
        cat >> "${{ github.workspace }}/wild_gki.fragment" << 'EOF'
        # Mountify Support
        CONFIG_OVERLAY_FS=y
        CONFIG_TMPFS_XATTR=y
        CONFIG_TMPFS_POSIX_ACL=y

        # KPatch-Next Support
        CONFIG_KALLSYMS=y
        CONFIG_KALLSYMS_ALL=y

        EOF
        # CONFIG_TRIM_UNUSED_KSYMS is not set
        # add this here for later


    - name: Add RUST build configs
      shell: bash
      if: ${{ inputs.kernel_version == '6.12' && inputs.android_version == 'android16' && inputs.sublevel <= '38' }}
      run: |
        set -euo pipefail
        echo "Add Build based configs"
        cat >> "${{ github.workspace }}/wild_gki.fragment" << 'EOF'
        # CONFIG_ANDROID_BINDER_IPC_RUST is not set
        CONFIG_ANDROID_BINDER_IPC_RUST_DUMMY=m
        EOF
